# Generated by Django 4.1.1 on 2023-01-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
